---

- hosts: webserver
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - geerlingguy.composer

